name: kuran_ezber
description: "Kur'an-覺 Kerim Ezber Uygulamas覺 - Modern ve kullan覺c覺 dostu mobil uygulama"
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # UI ve State Management
  cupertino_icons: ^1.0.8
  provider: ^6.1.2

  # Network ve API
  http: ^1.2.1

  # Storage
  shared_preferences: ^2.2.3

  # Audio
  audioplayers: ^6.4.0

  # URL Launcher
  url_launcher: ^6.3.1

  # Fonts
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: UthmanicHafs
      fonts:
        - asset: assets/fonts/UthmanTSVer1.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/AmiriQuran-Regular.ttf
          weight: 400
